name: Main

on: push

jobs:
  test-ubuntu:
    # Run test on ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Run tests
        run: ./test.sh
